platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: bin_gpbackup_1.0.0_and_1.7.1
  optional: true
- name: pgcrypto43
  optional: true
- name: gppkgs

params:
  GPBACKUP_VERSION:
  OS: RHEL8

run:
  path: gpbackup/ci/scripts/all-tests.bash
