platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/ccp
    tag: '7'

inputs:
- name: ccp_src
- name: cluster_env_files
- name: boostfs_installer
- name: gpbackup

params:
  DD_SOURCE_HOST:
  DD_USER:
  DD_PW:

run:
  path: gpbackup/ci/scripts/boostfs-install.bash
