platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup_tar
- name: gpbackup-tools-versions
- name: gp-pkg

outputs:
- name: gppkgs

params:
  OS:

run:
  path: gpbackup/ci/scripts/build-gppkgs.bash
