platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: gpbackup_s3_plugin
  path: go/src/github.com/greenplum-db/gpbackup-s3-plugin
- name: gpbackup_manager_src
  path: go/src/github.com/pivotal/gp-backup-manager

outputs:
- name: output_deps
- name: go_components

run:
  path: go/src/github.com/greenplum-db/gpbackup/ci/scripts/build-go-binaries.bash
