platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: gpbackup-go-components
- name: ddboost_components

outputs:
- name: gpbackup_tar

run:
  path: gpbackup/ci/scripts/build-os-tars.bash


