platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: dummy_seclabel
  optional: true
- name: gppkgs

params:
  default_ami_user: root
  OS:

run:
  path: gpbackup/ci/scripts/gpbackup-tests.bash
