platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: backup_artifact_resource
- name: regression_dump

run:
  path: gpbackup/ci/scripts/gprestore-regression.bash


