platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files

params:
  GPBACKUP_VERSION:

run:
  path: gpbackup/ci/scripts/integration-tests-fixed-version.bash
