platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:

run:
  path: gpbackup/ci/scripts/s3-plugin-tests.bash
