platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
  REGION:
  OS: RHEL7

run:
  path: gpbackup/ci/scripts/s3-plugin-perf.bash
