platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

outputs:
- name: cluster-metadata

params:
  GOOGLE_CREDENTIALS:
  OS: RHEL8

run:
  path: gpbackup/ci/scripts/scale-perf-load.bash
