platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

params:
  RESULTS_LOG_FILE:
  RESULTS_DATABASE_HOST: 
  RESULTS_DATABASE_USER:
  RESULTS_DATABASE_NAME:
  RESULTS_DATABASE_PASSWORD:
  GOOGLE_CREDENTIALS:
  GOOGLE_PROJECT_ID:
  GOOGLE_ZONE:
  GOOGLE_SERVICE_ACCOUNT:
  BUCKET_NAME:
  OS: RHEL

run:
  path: gpbackup/ci/scripts/scale_perf_tests.bash
