platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: gppkgs
- name: cluster-metadata

params:
  RESULTS_LOG_FILE:
  RESULTS_DATABASE_HOST: 
  RESULTS_DATABASE_USER:
  RESULTS_DATABASE_NAME:
  RESULTS_DATABASE_PASSWORD:
  OS: RHEL

run:
  path: gpbackup/ci/scripts/scale-perf-tests.bash
