platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: scale_schema
- name: gppkgs

run:
  path: gpbackup/ci/scripts/scale-tests.bash
