platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: scale_schema
- name: gppkgs
- name: gp-pkg
  optional: true

params:
  OS: RHEL8

run:
  path: gpbackup/ci/scripts/scale-tests.bash
