platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: ccp_src
- name: cluster_env_files
- name: scale_schema

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    ccp_src/aws/setup_ssh_to_cluster.sh

    cat <<SCRIPT > /tmp/run_tests.bash
    set -ex
        cat << ENV_SCRIPT > env.sh
        export GOPATH=/home/gpadmin/go
        source /usr/local/greenplum-db-devel/greenplum_path.sh
        export PGPORT=5432
        export MASTER_DATA_DIRECTORY=/data/gpdata/master/gpseg-1
        export PATH=\\\$GOPATH/bin:/usr/local/go/bin:\\\$PATH
    ENV_SCRIPT

    export GOPATH=/home/gpadmin/go
    chown gpadmin:gpadmin -R \$GOPATH
    chmod +x env.sh
    source env.sh
    gpconfig --skipvalidation -c fsync -v off
    gpstop -u

    pushd \$GOPATH/src/github.com/greenplum-db/gpbackup
        make depend
    popd

    tar -xvf scale_db1.tgz
    createdb scaledb -T template0

    psql -f scale_db1.sql -d scaledb -v client_min_messages=error -q

    cd \$GOPATH/src/github.com/greenplum-db/gpbackup
    make build
    make install_helper

    log_file=/tmp/gpbackup.log
    time pg_dump -s scaledb > /data/gpdata/pg_dump.sql
    time gpbackup --dbname scaledb --backup-dir /data/gpdata/ --metadata-only --verbose | tee "\$log_file"

    timestamp=\$(head -5 "\$log_file" | grep "Backup Timestamp " | grep -Eo "[[:digit:]]{14}")
    gprestore --timestamp "\$timestamp" --backup-dir /data/gpdata/ --redirect-db=scaledb_res --create-db

    SCRIPT

    ssh -t centos@mdw "sudo yum -y install wget git && wget https://storage.googleapis.com/golang/go1.9.3.linux-amd64.tar.gz && tar -xzf go1.9.3.linux-amd64.tar.gz && sudo mv go /usr/local"
    chmod +x /tmp/run_tests.bash
    scp /tmp/run_tests.bash mdw:/home/gpadmin/run_tests.bash
    ssh -t mdw "mkdir -p /home/gpadmin/go/src/github.com/greenplum-db"
    scp -r go/src/github.com/greenplum-db/gpbackup mdw:/home/gpadmin/go/src/github.com/greenplum-db/gpbackup
    scp -r scale_schema/scale_db1.tgz mdw:/home/gpadmin/
    ssh -t mdw "bash /home/gpadmin/run_tests.bash"
