platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: dummy_seclabel
  optional: true

params:
  default_ami_user: rocky

run:
  path: gpbackup/ci/scripts/setup-cluster-env.bash
