platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: dummy_seclabel
  optional: true

params:
  default_ami_user: centos

run:
  path: gpbackup/ci/scripts/setup-centos-env.bash
