platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: 11-beta

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gpbackup-dependencies
- name: gppkgs

run:
  path: gpbackup/ci/scripts/sles-tests.bash
