platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup_manager_src
- name: gppkgs

run:
  path: gpbackup/ci/scripts/test-gpbackup-manager.bash
