platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: gpdb_src
- name: bin_gpdb
- name: dummy_seclabel
  optional: true
- name: gppkgs

params:
  REQUIRES_DUMMY_SEC:
  OS: RHEL
  LOCAL_CLUSTER_SIZE: 3

run:
  path: gpbackup/ci/scripts/test-on-local-cluster.bash
