platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup
- name: dummy_seclabel
  optional: true
- name: gpbackup-dependencies
- name: gppkgs

params:
  REQUIRES_DUMMY_SEC:
  OS: RHEL

run:
  path: gpbackup/ci/scripts/test-on-local-cluster.bash
