platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: gpdb_src
- name: bin_gpdb
- name: dummy_seclabel
  optional: true
- name: gppkgs
- name: gp-pkg
  optional: true

params:
  REQUIRES_DUMMY_SEC:
  LOCAL_CLUSTER_SIZE: 3
  OS: RHEL8

run:
  path: gpbackup/ci/scripts/test-on-local-cluster.bash
