platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: ccp_src
- name: dummy_seclabel
- name: cluster_env_files
- name: gpbackup-dependencies
- name: gppkgs

run:
  path: go/src/github.com/greenplum-db/gpbackup/ci/scripts/ubuntu-tests.bash


