---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    cd $GOPATH/src/github.com/greenplum-db/gpbackup
    make depend
    make unit
