platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: release_components_rhel6
- name: release_components_rhel7
- name: release_components_rhel8
- name: release_components_rhel9
- name: release_components_ubuntu
- name: gpbackup-release-license
- name: pivnet_release_cache
- name: gppkgs
- name: tanzunet_client

outputs:
- name: workspace

run:
  path: gpbackup/ci/scripts/update-metadata.bash
