platform: linux

image_resource:
  type: docker-image

inputs:
- name: gppkgs
- name: github_release_components_rc
- name: gpbackup
- name: gpbackup-release-license
- name: pivnet_release_cache

outputs:
- name: workspace

run:
  path: gpbackup/ci/scripts/update-metadata.bash