# Fly this pipeline with the command: 
# fly -t TARGET sp -p gpbackup_clean_plugin_storage -c gpbackup/ci/cleanup/plugin-cleanup.yml -v gpbackup-git-branch=main -v source_host=SOURCE_IP -v dest_host=DEST_IP
---
##############################################
groups:
- name: all
  jobs:
  - clean-plugin-storage
##############################################

##############################################
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
##############################################

##############################################
resources:
- name: weekly-trigger
  type: time
  source:
    location: America/Los_Angeles
    days: [Sunday]
    start: 6:00 AM
    stop: 7:00 AM

- name: rocky8-gpdb6-image
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-rocky8-test
    tag: latest

- name: gpbackup
  type: git
  icon: github-circle
  source:
    uri: https://github.com/greenplum-db/gpbackup
    branch: ((gpbackup-git-branch))

##############################################

##############################################
anchors:
- &ddboost_params
  # TODO -- this is currently flown by providing with IP addresses passed to command line.  
    # This prevents needing to duplicate dev/prod files, and also avoids rewriting gen_pipeline.py
    # If we move to a one-concourse approach, these can easily be interpolated from Vault again
  DD_SOURCE_HOST: ((source_host))
  DD_DEST_HOST: ((dest_host))
  DD_SYSADMIN_PW: ((dp/prod/datadomain_sysadmin_password_gcp))
##############################################

##############################################
jobs:
- name: clean-plugin-storage
  plan: 
  - in_parallel:
    - get: rocky8-gpdb6-image
    - get: gpbackup
    - get: weekly-trigger
      trigger: true
  - task: clean-plugins
    image: rocky8-gpdb6-image
    params:
      <<: *ddboost_params
    config:
      platform: linux
      inputs:
        - name: gpbackup
      run: 
        path: "bash"
        args:
          - gpbackup/ci/scripts/call-clean-ddboost.bash
##############################################
